import pandas as pd

# สร้างข้อมูลจำลอง
data = {
    "Outlook": [
        "Sunny",
        "Sunny",
        "Overcast",
        "Rainy",
        "Rainy",
        "Rainy",
        "Overcast",
        "Sunny",
        "Sunny",
        "Rainy",
        "Sunny",
        "Overcast",
        "Overcast",
        "Rainy",
    ],
    "Temperature": [
        "Hot",
        "Hot",
        "Hot",
        "Mild",
        "Cool",
        "Cool",
        "Cool",
        "Mild",
        "Cool",
        "Mild",
        "Mild",
        "Mild",
        "Hot",
        "Mild",
    ],
    "Humidity": [
        "High",
        "High",
        "High",
        "High",
        "Normal",
        "Normal",
        "Normal",
        "High",
        "Normal",
        "Normal",
        "Normal",
        "High",
        "Normal",
        "High",
    ],
    "Windy": [
        False,
        True,
        False,
        False,
        False,
        True,
        True,
        ~False,
        False,
        False,
        True,
        True,
        False,
        True,
    ],
    "Play": [
        "No",
        "No",
        "Yes",
        "Yes",
        "Yes",
        "No",
        "Yes",
        "No",
        "Yes",
        "Yes",
        "Yes",
        "Yes",
        "Yes",
        "No",
    ],
}

# df = pd.read_csv("tennis.csv")  # หรือถ้าสร้างเองในโค้ดใช้ df = pd.DataFrame(data)
df = pd.DataFrame(data)

print("ตัวอย่างข้อมูล:")
print(df.head())
